config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'searches/index'
  root to:'pages#home'

  post 'searches', to: 'searches#new'
  get 'searches/:id', to: 'searches#show'

  get '/.well-known/acme-challenge/:id' => 'pages#letsencrypt'


  # Sidekiq Web UI, only for admins.
  require "sidekiq/web"
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end


end

app/views/pages/home.html.erb
<div class="banner">
    <div class="typejs"><span id="banner-typed-text"></span></div>
    <div class="form-container">
        <%= simple_form_for Search.new, :url => searches_path, :method => :post, html: { class: 'form text-center' } do |f| %>
            <%= f.input :keyword, label: false, placeholder: 'Enter a job keywords. e.g. Big Data', required: true %>
            <div id="search-message" class="text-center"><i class="fas fa-spinner fa-spin"></i> Analyzing...</div>
        <% end %>
    </div>
</div>

<div class="tabs">
  <div class="tab" id="show_popular" data-state = "active">
    <h3>Most Popular</h3>
    <% unless @search_rank.empty? %>
    <p>No.1 <%= @search_rank[0][0] %></p>
    <% end %>
  </div>
  <div class="tab" id="show_opportunity">
    <h3>Most Opportuinies</h3>
    <% unless @chance_rank.empty? %>
    <p>No.1 <%= @chance_rank[0][0] %></p>
    <% end %>
  </div>
  <div class="tab" id="show_high_salary_job">
    <h3>High Pay Jobs</h3>
    <% unless @job_salary_rank.empty? %>
    <p>No.1 <%= @job_salary_rank[0][0] %></p>
    <% end %>
  </div>
  <div class="tab" id="show_high_salary_location">
    <h3>High Pay Locations</h3>
    <% unless @location_salary_rank.empty? %>
    <p>No.1 <%= @location_salary_rank[0][0] %></p>
    <% end %>
  </div>
</div>

<div class="chart-section">
    <canvas id="chart" width="400" height="400"></canvas>
</div>

<div class="summary">
        <% if @search_rank.size > 3 %>
            <h4>According to <%= @search_qty %> searches so far...</h4>
            <h4>The most popular keywords are <%= @search_rank[0][0] %>, <%= @search_rank[1][0] %>, <%= @search_rank[2][0] %>...
            <br>
            <%= @chance_rank[0][0] %>, <%= @chance_rank[1][0] %>, <%= @chance_rank[2][0] %>... currently provides most opportunities!</h4>
            <h4>Want to earn more money?</h4>
            <h4>Find jobs related to <%= @job_salary_rank[0][0] %>, <%= @job_salary_rank[1][0] %>, or <%= @job_salary_rank[2][0] %>!
            <br>You can get higher salary in <%= @location_salary_rank[0][0] %>, <%= @location_salary_rank[1][0] %>, and <%= @location_salary_rank[2][0] %>!<h4>Of course, no guarantee of better life quality.</h4>
        <% end %>
</div>

<div class="about" style="margin: 30px;">
        <h2 class="text-center">Contact me through <a href="mailto:cwhuang0523@gmail.com">email</a> if you have any suggestion!</h2>
</div>



<%# data %>
<%= content_tag :div, class: "home_page" do %>
<% end %>


<%= content_tag :div, class: "show_popular", data: {id: 'chart', labels: @search_rank.map {|i| i[0]}, data: @search_rank.map {|i| i[1]}, labelText:"searches",titleText:"POPULAR SEARCH TOP 10" } do %>
<% end %>

<%= content_tag :div, class: "show_opportunity", data: {id: 'chart', labels: @chance_rank.map {|i| i[0]}, data: @chance_rank.map {|i| i[1]}, labelText:"qty",titleText:"MOST OPPORTUNITIES LOCATION TOP 10" } do %>
<% end %>

<%= content_tag :div, class: "show_high_salary_job", data: {id: 'chart', labels: @job_salary_rank.map {|i| i[0]}, data: @job_salary_rank.map {|i| i[1]}, labelText:"average salary(RMB/month)",titleText:"HIGH SALARY TOP 10 (RMB/MONTH)" } do %>
<% end %>

<%= content_tag :div, class: "show_high_salary_location", data: {id: 'chart', labels: @location_salary_rank.map {|i| i[0]}, data: @location_salary_rank.map {|i| i[1]}, labelText:"average salary(RMB/month)",titleText:"HIGH SALARY LOCATION TOP 10" } do %>
<% end %>